/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrinhos.carrinhosthegame;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import org.bson.Document;

/**
 *
 * @author 22159666
 */
public class Game extends javax.swing.JFrame {

    public Game() {
        initComponents();
        URL url = this.getClass().getResource("/tony.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
        setLocationRelativeTo(null);
        barJogador.setVisible(false);
        barOponente.setVisible(false);
        acelerar.setVisible(false);
        acelerar.setEnabled(false);
        correr.setVisible(false);


        /* QUASE FUNCIONA TECLAS
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_UP,0);
        Action actionListener = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            }
        }
    };

    InputMap inputMap = this.getRootPane().getInputMap(
            JComponent.WHEN_IN_FOCUSED_WINDOW);
    inputMap.put(stroke, "ATIVA");

    this.getRootPane().getActionMap().put("ATIVA", actionListener);
         */
    }
    int vitoriaVic = 0;
    int derrotaVic = 0;
    int DeroJog = 0;
    int vitoriaJog = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cards = new javax.swing.JPanel();
        charSelect = new javax.swing.JPanel();
        Imagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listaChar = new javax.swing.JComboBox<>();
        select = new javax.swing.JButton();
        gamePlay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rankBtn = new javax.swing.JButton();
        correr = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        selectEnemy = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        nameVen = new javax.swing.JLabel();
        barOponente = new javax.swing.JProgressBar();
        barJogador = new javax.swing.JProgressBar();
        acelerar = new javax.swing.JButton();
        Selecionar = new javax.swing.JButton();
        persoEscolhido = new javax.swing.JLabel();
        rank = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        Imagem1 = new javax.swing.JLabel();
        Imagem2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        quantVitJog = new javax.swing.JLabel();
        quantDeroJog = new javax.swing.JLabel();
        quantVitVic = new javax.swing.JLabel();
        quantDeroVic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cards.setLayout(new java.awt.CardLayout());

        Imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Escolha o seu personagem");

        listaChar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tonny Tunado", "Kombo", "Cris Crash", "Senhor V8", "Campeão", "Simone", "Tobias", "Michael Chumassa", "Akira", "Pé Grande", "Bongo", "MC Carrius", "MC Truta" }));
        listaChar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCharMouseClicked(evt);
            }
        });
        listaChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCharActionPerformed(evt);
            }
        });

        select.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        select.setText("Selecionar");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout charSelectLayout = new javax.swing.GroupLayout(charSelect);
        charSelect.setLayout(charSelectLayout);
        charSelectLayout.setHorizontalGroup(
            charSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, charSelectLayout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, charSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(charSelectLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(listaChar, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(charSelectLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(select)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        charSelectLayout.setVerticalGroup(
            charSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charSelectLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(listaChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(select)
                .addGap(107, 107, 107))
        );

        cards.add(charSelect, "charSelect");

        gamePlay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gamePlayKeyPressed(evt);
            }
        });
        gamePlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tony.png"))); // NOI18N
        gamePlay.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 69, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Seu Personagem");
        gamePlay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 168, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Escolha o seu oponente");
        gamePlay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 168, -1, -1));

        jLabel6.setText("Resultado da última corrida:");
        gamePlay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 407, -1, -1));

        rankBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rankBtn.setText("Progresso");
        rankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankBtnActionPerformed(evt);
            }
        });
        gamePlay.add(rankBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 543, -1, -1));

        correr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        correr.setText("Correr");
        correr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correrActionPerformed(evt);
            }
        });
        gamePlay.add(correr, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 494, -1, -1));

        sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        gamePlay.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 543, -1, -1));

        selectEnemy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Tonny Tunado", "Kombo", "Cris Crash", "Senhor V8", "Campeão", "Simone", "Tobias", "Michael Chumassa", "Akira", "Pé Grande", "Bongo", "MC Carrius", "MC Truta" }));
        gamePlay.add(selectEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 244, 222, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandeiras.png"))); // NOI18N
        gamePlay.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 185, -1, -1));

        nameVen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameVen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gamePlay.add(nameVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 441, 160, 47));

        barOponente.setStringPainted(true);
        gamePlay.add(barOponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 342, 222, 35));

        barJogador.setStringPainted(true);
        gamePlay.add(barJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 342, 222, 35));

        acelerar.setText("Acelerar");
        acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acelerarActionPerformed(evt);
            }
        });
        gamePlay.add(acelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 429, -1, -1));

        Selecionar.setText("Selecionar");
        Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });
        gamePlay.add(Selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 347, -1, -1));

        persoEscolhido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png"))); // NOI18N
        gamePlay.add(persoEscolhido, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 199, 200, 120));

        cards.add(gamePlay, "gamePlay");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setText("Progresso");

        voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        Imagem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/victor.png"))); // NOI18N

        Imagem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png"))); // NOI18N

        jLabel9.setText("Vitórias");

        jLabel10.setText("Derrotas");

        jLabel12.setText("Vitórias");

        jLabel13.setText("Derrotas");

        quantVitJog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantVitJog.setText("0");

        quantDeroJog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantDeroJog.setText("0");

        quantVitVic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantVitVic.setText("0");

        quantDeroVic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantDeroVic.setText("0");

        javax.swing.GroupLayout rankLayout = new javax.swing.GroupLayout(rank);
        rank.setLayout(rankLayout);
        rankLayout.setHorizontalGroup(
            rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankLayout.createSequentialGroup()
                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rankLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rankLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Imagem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rankLayout.createSequentialGroup()
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantVitJog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantDeroJog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Imagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rankLayout.createSequentialGroup()
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(quantVitVic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(quantDeroVic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(60, 60, 60))
            .addGroup(rankLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rankLayout.setVerticalGroup(
            rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantVitJog)
                    .addComponent(quantDeroJog)
                    .addComponent(quantVitVic)
                    .addComponent(quantDeroVic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cards.add(rank, "rank");

        getContentPane().add(cards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void rankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankBtnActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards, "rank");        // TODO add your handling code here:
    }//GEN-LAST:event_rankBtnActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.previous(cards);    // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        CRUD cru = new CRUD();
        Cadastro cad = new Cadastro();
        Login log = new Login();
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards, "gamePlay");
        String Charc = listaChar.getSelectedItem().toString();

    }//GEN-LAST:event_selectActionPerformed

    private void listaCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCharActionPerformed
        String Charc = listaChar.getSelectedItem().toString();
        if (null != Charc)
            switch (Charc) {
                case "Tonny Tunado":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tonytunado.jpg")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tonytunado.jpg")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tonytunado.jpg")));
                    break;
                case "Bongo":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bongo.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bongo.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bongo.png")));
                    break;
                case "Campeão":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campeao.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campeao.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/campeao.png")));
                    break;
                case "Cris Crash":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cris.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cris.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cris.png")));
                    break;
                case "Kombo":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kombo.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kombo.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kombo.png")));
                    break;
                case "MC Carrius":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mccarrius.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mccarrius.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mccarrius.png")));
                    break;
                case "MC Truta":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctruta.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctruta.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mctruta.png")));
                    break;
                case "Michael Chumassa":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/michael.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/michael.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/michael.png")));
                    break;
                case "Pé Grande":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegrande.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegrande.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegrande.png")));
                    break;
                case "Senhor V8":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senhorv8.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senhorv8.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senhorv8.png")));
                    break;
                case "Simone":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simone.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simone.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simone.png")));
                    break;
                case "Akira":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/akira.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/akira.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/akira.png")));
                    break;
                case "Tobias":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tobias.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tobias.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tobias.png")));
                    break;
                case "Selecione":
                    Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png")));
                    Imagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png")));
                    persoEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escolherPer.png")));
                    break;
                default:
                    break;
            }
    }//GEN-LAST:event_listaCharActionPerformed

    private void listaCharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCharMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCharMouseClicked

    private void gamePlayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gamePlayKeyPressed
    }//GEN-LAST:event_gamePlayKeyPressed

    private void acelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acelerarActionPerformed
        String Charc = listaChar.getSelectedItem().toString();
        CRUD cru = new CRUD();

        if (barJogador.getValue() < 100) {

            barJogador.setValue(barJogador.getValue() + 3);
            barJogador.setString(String.valueOf(barJogador.getValue()) + "%");

        } else if (barJogador.getValue() == 100) {
            JOptionPane.showMessageDialog(null, "Parabéns!!!" + "\nVocê Venceu!");
            barOponente.setValue(0);
            barJogador.setValue(0);
            barJogador.setString(0 + "%");
            barJogador.setVisible(false);
            barOponente.setVisible(false);
            acelerar.setVisible(false);
            acelerar.setEnabled(false);
            correr.setVisible(false);
            selectEnemy.setEnabled(true);
            nameVen.setText(Charc);
            vitoriaJog += 1;
            quantVitJog.setText("" + vitoriaJog);
            cru.atualizarVitBanco(Charc, vitoriaJog);
        }
        if (vitoriaJog == 10) {
            JOptionPane.showMessageDialog(null, "Não é possivel" + " \nVocê ganhou o torneio!!!");
            JOptionPane.showMessageDialog(null, "Meus parabéns agora pode ir embora para casa!");
            Login log = new Login();
            log.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_acelerarActionPerformed
    private void correrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correrActionPerformed
        CRUD cru = new CRUD();
        String enemy = selectEnemy.getSelectedItem().toString();
        String Charc = listaChar.getSelectedItem().toString();
        acelerar.setEnabled(true);

        Random aleatorio = new Random();
        int num_ale = aleatorio.nextInt(2);

        if (num_ale == 0) {
            vitoriaVic += 1;
            cru.atualizarVitBanco("Victor", vitoriaVic);
            cru.atualizarValIG(Charc, vitoriaVic, derrotaVic);
            int vitor = cru.vito;
            quantVitVic.setText("" + vitor);
        } else if (num_ale == 1) {
            derrotaVic += 1;
            cru.atualizarDeroBanco(Charc, derrotaVic);
            cru.atualizarValIG(Charc, vitoriaVic, derrotaVic);
            int derror = cru.dero;
            quantDeroVic.setText("" + derror);
        }
        if (vitoriaVic == 10) {
            JOptionPane.showMessageDialog(null, "Oh SHIT" + " \no Victor ganhou o torneio");
            JOptionPane.showMessageDialog(null, "Tenta denovo mais tarde seu PASPALHO :)");
            Login log = new Login();
            log.setVisible(true);
            dispose();
        }

        new Thread() {

            public void run() {
                while (barOponente.getValue() < 100) {
                    try {
                        sleep(1000);
                        barOponente.setValue(barOponente.getValue() + 10);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (barJogador.getValue() == 100) {
                        break;
                    }
                }
                if (barOponente.getValue() == 100) {
                    JOptionPane.showMessageDialog(null, "Parabéns!!!" + "\nVocê Perdeu!");
                    nameVen.setText(enemy);
                    barOponente.setValue(0);
                    barJogador.setValue(0);
                    barJogador.setVisible(false);
                    barOponente.setVisible(false);
                    acelerar.setVisible(false);
                    acelerar.setEnabled(false);
                    correr.setVisible(false);
                    selectEnemy.setEnabled(true);
                    DeroJog += 1;
                    quantDeroJog.setText("" + DeroJog);
                    cru.atualizarVitBanco(Charc, DeroJog);

                }
            }
        }.start();


    }//GEN-LAST:event_correrActionPerformed

    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed
        String enemy = selectEnemy.getSelectedItem().toString();
        String Charc = listaChar.getSelectedItem().toString();
        if (enemy == "Selecione") {
            JOptionPane.showMessageDialog(null, "Selecione um Oponente");
        } else if (Charc == enemy) {
            JOptionPane.showMessageDialog(null, "Pera um pouco ... esse é você mesmo!" + "\nEscolhe outro oponente ae cara!");
        } else {
            barJogador.setVisible(true);
            barOponente.setVisible(true);
            acelerar.setVisible(true);
            selectEnemy.setEnabled(false);
            correr.setVisible(true);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_SelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel Imagem1;
    private javax.swing.JLabel Imagem2;
    private javax.swing.JButton Selecionar;
    private javax.swing.JButton acelerar;
    private javax.swing.JProgressBar barJogador;
    private javax.swing.JProgressBar barOponente;
    private javax.swing.JPanel cards;
    private javax.swing.JPanel charSelect;
    private javax.swing.JButton correr;
    private javax.swing.JPanel gamePlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> listaChar;
    private javax.swing.JLabel nameVen;
    private javax.swing.JLabel persoEscolhido;
    private javax.swing.JLabel quantDeroJog;
    private javax.swing.JLabel quantDeroVic;
    private javax.swing.JLabel quantVitJog;
    private javax.swing.JLabel quantVitVic;
    private javax.swing.JPanel rank;
    private javax.swing.JButton rankBtn;
    private javax.swing.JButton sair;
    private javax.swing.JButton select;
    private javax.swing.JComboBox<String> selectEnemy;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
